name = "blog"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 预览环境变量
[env.preview.vars]
NODE_VERSION = "18.18.0"
NEXT_PUBLIC_SITE_URL = "https://hackathonweekly.com"
NEXT_PUBLIC_SITE_NAME = "HackathonWeekly"
NEXT_PUBLIC_SITE_DESCRIPTION = "Your Weekly Hackathon Community"
NEXT_PUBLIC_ENV = "preview"
NEXT_PUBLIC_API_URL = "https://preview.hackathonweekly.com"
NEXT_PUBLIC_ASSETS_URL = "https://preview.hackathonweekly.com"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
compatibility_flags = ["nodejs_compat"]

# 生产环境变量
[env.production.vars]
NODE_VERSION = "18.18.0"
NEXT_PUBLIC_SITE_URL = "https://hackathonweekly.com"
NEXT_PUBLIC_SITE_NAME = "HackathonWeekly"
NEXT_PUBLIC_SITE_DESCRIPTION = "Your Weekly Hackathon Community"
NEXT_PUBLIC_ENV = "production"
NEXT_PUBLIC_API_URL = "https://hackathonweekly.com"
NEXT_PUBLIC_ASSETS_URL = "https://hackathonweekly.com"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
compatibility_flags = ["nodejs_compat"]